apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    scrape_interval: 15s

    scrape_configs:
      - job_name: 'flask_app'
        static_configs:
          - targets: ['flask-app:8080']
